# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"extract_text": "01_text_extractor.ipynb",
         "extract_texts": "01_text_extractor.ipynb",
         "Article": "02_article.ipynb",
         "make_articles": "02_article.ipynb"}

modules = ["text_extractor.py",
           "article.py",
           "review.py",
           "visualization.py"]

doc_url = "https://hgzech.github.io/literature_review/"

git_url = "https://github.com/hgzech/literature_review/tree/master/"

def custom_doc_links(name): return None
