# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_text_extractor.ipynb (unless otherwise specified).

__all__ = ['extract_text', 'extract_texts']

# Cell
import scipdf
import json
import os

# Cell
def extract_text(infolder, outfolder, filename):
    if not os.path.isdir(outfolder):
        os.mkdir(outfolder)
    inpath = os.path.join(infolder, filename)
    outpath = os.path.join(outfolder, filename.split('.')[0]+'.json')
    if not os.path.isfile(outpath):
        article_dict = scipdf.parse_pdf_to_dict(inpath)
        with open(outpath, 'w') as fp:
            json.dump(article_dict, fp)

# Cell
def extract_texts(infolder, outfolder):
    files = os.listdir(infolder)
    assert len(files) == len(set(files)), "Duplicate files"
    for file in files:
        if not file.endswith('.pdf'):
            print("%s not a pdf?"%file)
        else:
            print("Extracting %s ..."%file)
            extract_text(infolder, outfolder, file)